let num1 = prompt("Escolha um número")
let num2 = prompt("Escolha mais um número")

console.log ("O primeiro numero é maior que segundo?")
console.log (num1 > num2)
console.log ("O primeiro numero é igual ao segundo?")
console.log (num1 === num2)
console.log ("O primeiro numero é divisível pelo segundo?")
console.log (num1%num2===0)
console.log ("O segundo numero é divisível pelo primeiro?")
console.log (num2%num1===0)